### ISSUE TITLE
DB test data

### ISSUE THREAD

**Issue by sparkoo** [sparkoo/speakup#28]
It would be nice for development to have some fake data in DB. It can be some gradle task that fill DB with such data. 
Faker library can be used for that.

**Comment by D3ryk** [comment]
Since we are using flyway for DB migration. We can utilize this interface and which offeres oportunity to implement custom hooks https://flywaydb.org/documentation/api/javadoc/org/flywaydb/core/api/callback/FlywayCallback. After implementing you can just add fully qualified name to config under callback directive @see https://flywaydb.org/documentation/gradle/migrate.
